# Generated by Django 4.2.4 on 2023-08-26 15:43

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
